### ISSUE TITLE
Problem of running dataset/make_training_data.py script

### ISSUE THREAD

**Issue by ruqing00** [kentsommer/pytorch-value-iteration-networks#14]
Hi

When I tried to run the `make_training_data.py` script to generate the `gridworld.npz` file, I got the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/gridworld_28x28.npz'
```
And I found that line 101 should be modified as follows:
```python
save_path = "gridworld_{0}x{1}".format(dom_size[0], dom_size[1])
```

**Comment by JYTCV** [comment]
Have you implemented the program of Mars data experiment? Can you share how to generate a Mars data set?

**Comment by LTH40025** [comment]
hi ,i faced this problem , can you show your floder for me?
`Traceback (most recent call last):
  File ".\make_training_data.py", line 9, in <module>
    from domains.gridworld import *`

**Comment by LTH40025** [comment]
hi ,i faced this problem , can you show your floder for me?
`Traceback (most recent call last):
  File ".\make_training_data.py", line 9, in <module>
    from domains.gridworld import *
ModuleNotFoundError: No module named 'domains'`

**Comment by ruqing00** [comment]
> hi ,i faced this problem , can you show your floder for me? `Traceback (most recent call last): File ".\make_training_data.py", line 9, in <module> from domains.gridworld import * ModuleNotFoundError: No module named 'domains'`

Surely, I run this project in Pycharm with Windows, and here is my floder structure:
E:\PROJECT\PYTHON_PROJECT\VALUE_ITERATION_NETWORKS\KENTSOMMER_PYTORCH
│  download_weights_and_datasets.sh
│  LICENSE
│  model.py
│  README.md
│  requirements.txt
│  test.py
│  train.py
│
├─.idea
│  │  .gitignore
│  │  encodings.xml
│  │  kentsommer_pytorch.iml
│  │  misc.xml
│  │  modules.xml
│  │  other.xml
│  │  vcs.xml
│  │  workspace.xml
│  │
│  └─inspectionProfiles
│          profiles_settings.xml
│          Project_Default.xml
│
├─dataset
│  │  dataset.py
│  │  gridworld_16x16.npz
│  │  gridworld_28x28.npz
│  │  gridworld_8x8.npz
│  │  make_training_data.py
│  │  README.MD
│  │  __init__.py
│  │
│  └─__pycache__
│          dataset.cpython-37.pyc
│          __init__.cpython-37.pyc
│
├─domains
│  │  gridworld.py
│  │  __init__.py
│  │
│  └─__pycache__
│          gridworld.cpython-37.pyc
│          __init__.cpython-37.pyc
│
├─generators
│  │  obstacle_gen.py
│  │  __init__.py
│  │
│  └─__pycache__
│          obstacle_gen.cpython-37.pyc
│          __init__.cpython-37.pyc
│
├─results
│      16x16_1.png
│      16x16_2.png
│      28x28_1.png
│      28x28_2.png
│      8x8_1.png
│      8x8_2.png
│
├─trained
│      README.md
│      vin_8x8.pth
│
├─utility
│  │  utils.py
│  │  __init__.py
│  │
│  └─__pycache__
│          utils.cpython-37.pyc
│          __init__.cpython-37.pyc
│
└─__pycache__
        model.cpython-37.pyc

**Comment by LTH40025** [comment]
thanks, see my issue , i find my floder don't have domains floder; can you send to me
![image](https://github.com/kentsommer/pytorch-value-iteration-networks/assets/118742066/9c932fc0-b69a-4974-bec8-c0b340d1b8c9)

**Comment by LTH40025** [comment]
> Hi
> 
> When I tried to run the `make_training_data.py` script to generate the `gridworld.npz` file, I got the following error:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'dataset/gridworld_28x28.npz'
> ```
> 
> And I found that line 101 should be modified as follows:
> 
> ```python
> save_path = "gridworld_{0}x{1}".format(dom_size[0], dom_size[1])
> ```

I think your problem is your  save_path error
`save_path = "C:\\Users\\Desktop\\dataset\\gridworld_{0}x{1}".format(dom_size[0], dom_size[1])`

**Comment by ruqing00** [comment]
> > Hi
> > When I tried to run the `make_training_data.py` script to generate the `gridworld.npz` file, I got the following error:
> > ```
> > FileNotFoundError: [Errno 2] No such file or directory: 'dataset/gridworld_28x28.npz'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I found that line 101 should be modified as follows:
> > ```python
> > save_path = "gridworld_{0}x{1}".format(dom_size[0], dom_size[1])
> > ```
> 
> I think your problem is your save_path error `save_path = "C:\\Users\\Desktop\\dataset\\gridworld_{0}x{1}".format(dom_size[0], dom_size[1])`

Thank you very much for suggesting a solution, I have successfully solved the problem!
modify line 101 can also solve the problem:
```python
save_path = "gridworld_{0}x{1}".format(dom_size[0], dom_size[1])
```
