### ISSUE TITLE
Inconsistent tensor sizes when starting training

### ISSUE THREAD

**Issue by juancprzs** [kentsommer/pytorch-value-iteration-networks#2]
Hey there.
I'm trying to run 
```bash
python train.py --datafile dataset/gridworld_8x8.npz --imsize 8 --lr 0.005 --epochs 30 --k 10 --batch_size 128
```
But I get the following error
```bash
Number of Train Samples: 103926
Number of Test Samples: 17434
     Epoch | Train Loss | Train Error | Epoch Time
Traceback (most recent call last):
  File "train.py", line 147, in <module>
    train(net, trainloader, config, criterion, optimizer, use_GPU)
  File "train.py", line 40, in train
    outputs, predictions = net(X, S1, S2, config)
  File "/home/j1k1000o/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/user_home2/j1k1000o/j1k/VINs/pytorch-value-iteration-networks/model.py", line 44, in forward
    q = F.conv2d(torch.cat([r, v], 1), 
  File "/home/j1k1000o/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 897, in cat
    return Concat.apply(dim, *iterable)
  File "/home/j1k1000o/anaconda3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 317, in forward
    return torch.cat(inputs, dim)
RuntimeError: inconsistent tensor sizes at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generic/THCTensorMath.cu:141
```
I've executed 
```bash
./download_weights_and_datasets.sh
```
as well as
```bash
python ./dataset/make_training_data.py
```
And I'm running it on an Ubuntu 16.04, python 3.6 and with all the requirements installed.

Can you help me out?

**Comment by kentsommer** [comment]
Hi @j1k1000o 

Please see 47dd60d243748268a88155b37b2e0d8f9769facd which fixes this issue. 

Please pull and try again!

**Comment by juancprzs** [comment]
Thanks!!
