### ISSUE TITLE
Problem of running the test script

### ISSUE THREAD

**Issue by YantianZha** [kentsommer/pytorch-value-iteration-networks#4]
Hello,

I downloaded the data with the .sh downloading script you provided, I also got an nps weights file after training. When I ran the testing command I got the following error:
Traceback (most recent call last):
  File "/home/research/DL/VIN/pytorch-value-iteration-networks/test.py", line 158, in <module>
    main(config)
  File "/home/research/DL/VIN/pytorch-value-iteration-networks/test.py", line 85, in main
    _, predictions = vin(X_in, S1_in, S2_in, config)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/research/DL/VIN/pytorch-value-iteration-networks/model.py", line 64, in forward
    return logits, self.sm(logits)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 352, in __call__
    for hook in self._forward_pre_hooks.values():
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'Softmax' object has no attribute '_forward_pre_hooks'

Thanks for helping!

**Comment by kentsommer** [comment]
Hi @YantianZha 

I'm aware of this bug and will fix it as soon as I can set aside some time (likely not until this weekend). 

It is due to softmax no longer providing a default dimension. Due to how I am currently saving the weights, fixing this will require retraining. Along with the fix to this bug, I will also be updating how the weights are saved so that this type of issue can be fixed more quickly in the future.

**Comment by YantianZha** [comment]
Hi Kent,


Thanks!


Best,

Yantian


________________________________

**Comment by kentsommer** [comment]
Fixed with https://github.com/kentsommer/pytorch-value-iteration-networks/commit/15fefd5bb645f990cdad452f14208a115789edba
